entity.site_setting_entity.add_form:
  route_name: 'site_setting_entity.add_page'
  title: 'Add Site Setting'
entity.site_setting_entity_type.add_form:
  route_name: 'entity.site_setting_entity_type.add_form'
  title: 'Add Site Setting type'
  appears_on:
    - entity.site_setting_entity_type.collection
site_settings_group_entity.type_add:
  title: 'Add site settings group entity type'
  route_name: entity.site_setting_group_entity_type.add_form
  appears_on:
    - entity.site_setting_group_entity_type.collection
