# Site Setting entity.
entity.site_setting_entity.edit_form:
  route_name: entity.site_setting_entity.edit_form
  base_route: entity.site_setting_entity.canonical
  title: Edit

entity.site_setting_entity.delete_form:
  route_name: entity.site_setting_entity.delete_form
  base_route: entity.site_setting_entity.canonical
  title: Delete
  weight: 10

site_settings.admin:
  title: Site Settings
  route_name: entity.site_setting_entity.collection
  base_route: system.admin_content

# Site settings entity type.
entity.site_setting_entity_type.edit_form:
  title: 'Edit'
  route_name: entity.site_setting_entity_type.edit_form
  base_route: entity.site_setting_entity_type.edit_form

entity.site_setting_entity_type.collection:
  title: 'List'
  route_name: entity.site_setting_entity_type.collection
  base_route: entity.site_setting_entity_type.collection

# Site settings entity group.
entity.site_setting_group_entity_type.edit_form:
  title: 'Edit'
  route_name: entity.site_setting_group_entity_type.edit_form
  base_route: entity.site_setting_group_entity_type.edit_form

entity.site_setting_group_entity_type.collection:
  title: 'List'
  route_name: entity.site_setting_group_entity_type.collection
  base_route: entity.site_setting_group_entity_type.collection
