# Site settings entity.
entity.site_setting_entity.edit_form:
  route_name: entity.site_setting_entity.edit_form
  group: site_settings
  title: Edit

entity.site_setting_entity.delete_form:
  route_name: entity.site_setting_entity.delete_form
  group: site_settings
  title: Delete
  weight: 10

# Site settings entity type.
entity.site_setting_entity_type.edit_form:
  route_name: entity.site_setting_entity_type.edit_form
  group: site_setting_entity_type
  title: 'Edit'

entity.site_setting_entity_type.delete_form:
  route_name: entity.site_setting_entity_type.delete_form
  group: site_setting_entity_type
  title: 'Delete'
  weight: 10

# Site settings group.
entity.site_settings_group_entity.edit_form:
  route_name: entity.site_settings_group_entity.edit_form
  group: site_settings_group_entity
  title: 'Edit'

entity.site_settings_group_entity.delete_form:
  route_name: entity.site_settings_group_entity.delete_form
  group: site_settings_group_entity
  title: 'Delete'
  weight: 10
