site_settings.site_setting_entity_type.*:
  type: config_entity
  label: 'Site Setting type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    group:
      type: string
      label: 'Group'
    multiple:
      type: boolean
      label: 'Multiple'
